//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Site_open_WinForms.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://directum.akelon.com/Login.aspx?ReturnUrl=%2f")]
        public string KS {
            get {
                return ((string)(this["KS"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://club.directum.ru/webhelp/directumrx/web/index.html?provodnik_sistemy.htm")]
        public string WebInfoSite {
            get {
                return ((string)(this["WebInfoSite"]));
            }
            set {
                this["WebInfoSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://club.directum.ru/webhelp/directumrx/sds/index.html?sds_sreda_razrabotki_s" +
            "ds.htm")]
        public string DevelopInfoSite {
            get {
                return ((string)(this["DevelopInfoSite"]));
            }
            set {
                this["DevelopInfoSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://kmknowledge.akelon.com/")]
        public string KnowledgeSite {
            get {
                return ((string)(this["KnowledgeSite"]));
            }
            set {
                this["KnowledgeSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://service.akelon.com/app")]
        public string ServiceSite {
            get {
                return ((string)(this["ServiceSite"]));
            }
            set {
                this["ServiceSite"] = value;
            }
        }
    }
}
